# Generated by Django 3.1.2 on 2020-10-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expendedora', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (1,'Papa',2.50);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (2,'Queso',5.55);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (3,'Gaseosa',2.30);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (4,'Galletas',4.80);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (5,'Chocolate',3.20);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (6,'Mani',2.50);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (7,'Pasas',3.40);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (8,'Pan',0.50);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (9,'Triple',4.10);"),
        migrations.RunSQL("INSERT INTO expendedora_productos VALUES (10,'Té',2.30);"),

    ]
